[package]
name = "asyncstd"
version = "0.1.0"
authors = ["xargin <cao1988228@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.4.0" , features = ["unstable"] }
futures = "0.3.1"
