expr = {binary_op ~ ("and"|"or" ~ binary_op)*}
binary_op = { field ~ op ~ value}
field = { ASCII_ALPHANUMERIC+ }
op = { "=" | "in" | "!=" | "not in" | ">" | "<" | ">="| "<=" | "is"}
value = { string_literal | num_literal }

num_literal = @{
    "-"?
    ~ ("0" | ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*)
    ~ ("." ~ ASCII_DIGIT*)?
    ~ (^"e" ~ ("+" | "-")? ~ ASCII_DIGIT+)?
}

string_literal = ${ "\"" ~ string ~ "\"" }
string = @{ char* }
char = {
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

WHITESPACE = _{ " " | "\n" | "\r" }
