@startuml

(*)  --> "创建工单"
--> "编辑工单"
--> "提交工单"
--> “数据校验”
if "校验通过" then
--> [Yes] "工单审核"
    if "审核通过" then
        --> [Yes] "创建特征"
        --> "创建特征相关数据"
        --> "特征发布"
        --> (*)
    else
        --> [No] "编辑工单"
    endif
else
--> [No] "编辑工单"
endif
@enduml