package main

func main() {
	a := make([]string, 0, 100)
	println(a)
	println(len(a))
	println(cap(a))
	a = append(a, "fuck")
	println(a)
	println(len(a))
	println(cap(a))

	a = append(a, "fuck")
	println(a)
	println(len(a))
	println(cap(a))

	a = append(a, "fuck")
	println(a)
	println(len(a))
	println(cap(a))
	a = append(a, "fuck")
	println(a)
	println(len(a))
	println(cap(a))
	a = append(a, "fuck")
	println(a)
	println(len(a))
	println(cap(a))
	a = append(a, "fuck")
	println(a)
	println(len(a))
	println(cap(a))
	a = append(a, "fuck")
	println(a)
	println(len(a))
	println(cap(a))
	a = append(a, "fuck")
	println(a)
	println(len(a))
	println(cap(a))
}
